import { Link, useParams } from "react-router-dom";
import { CheckCircle2, Phone, MessageCircle } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { apiGet } from "@/lib/api";
import { Button } from "@/components/ui/button";
import type { Order } from "@/lib/types";
import { EMAIL, EMAIL_LINK, PHONE, PHONE_LINK, WHATSAPP_LINK } from "@/lib/brand";

export default function Confirmation() { const { orderId } = useParams(); const { data: order, isLoading } = useQuery({ queryKey: ["order", orderId], queryFn: () => apiGet<Order>(`/orders/${orderId}`), enabled: Boolean(orderId), retry: false }); return <div className="container section" data-testid="confirmation-page">{isLoading ? <div data-testid="confirmation-loading">Loading order confirmation…</div> : order ? <div className="confirmation-wrap"><div className="confirmation-icon"><CheckCircle2 size={28} /></div><p className="eyebrow">11 CR WHOLESALE BRIEF RECEIVED</p><h1 className="page-title">Thank you, <span>{order.customer_name.split(" ")[0]}.</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-400">Your 11 CR requirement is with the Kapda Godam desk. Keep your order ID handy — Mr. Shamsuddin or Mr. Tabrez will confirm availability and terms directly.</p><div className="order-id" data-testid="confirmation-order-id"><span>ORDER ID</span><strong>{order.order_id}</strong><BadgeStatus status={order.status} /></div><div className="confirmation-grid"><div className="summary-card" data-testid="confirmation-items"><p className="eyebrow">11 CR ASSORTMENT</p>{order.items.map((item) => <div className="mini-line" key={item.product_id}><div><strong>{item.name}</strong><span>Brand: {item.brand} · {item.sku} · {item.quantity} pieces</span></div><b>₹{item.line_total.toLocaleString("en-IN")}</b></div>)}<div className="summary-row total"><span>Estimated amount</span><strong data-testid="confirmation-estimated-total">₹{order.total_estimate.toLocaleString("en-IN")}</strong></div></div><div className="confirmation-contact"><p className="eyebrow">KAPDA GODAM CONFIRMATION DESK</p><h3>We will reach you shortly.</h3><p>Mr. Shamsuddin & Mr. Tabrez<br />Phone / WhatsApp: {PHONE}<br />Email: {EMAIL}</p><div className="mt-7 flex flex-wrap gap-3"><Button variant="outline" render={<a href={PHONE_LINK} />} data-testid="confirmation-phone-button"><Phone size={15} /> Call desk</Button><Button render={<a href={WHATSAPP_LINK} target="_blank" rel="noreferrer" />} data-testid="confirmation-whatsapp-button"><MessageCircle size={15} /> WhatsApp desk</Button><Button variant="ghost" render={<a href={EMAIL_LINK} />} data-testid="confirmation-email-button">Email desk</Button></div></div></div><Button variant="ghost" className="mt-8" render={<Link to="/" />} data-testid="confirmation-home-button">Back to 11 CR at Kapda Godam</Button></div> : <div data-testid="confirmation-error"><h1 className="page-title">Order not found.</h1><Link to="/" className="text-link mt-7">Back home</Link></div>}</div>; }
function BadgeStatus({ status }: { status: string }) { return <span className="status-pill" data-testid="confirmation-order-status">{status}</span>; }
