import { useQuery } from "@tanstack/react-query";
import { apiGet } from "@/lib/api";
import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, Factory, Layers3, Truck, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import ProductCard from "@/components/ProductCard";
import type { Product } from "@/lib/types";

const fetchProducts = () => apiGet<Product[]>("/products?featured=true");

export default function Home() {
  const { data = [] } = useQuery({ queryKey: ["products", "featured"], queryFn: fetchProducts, retry: false });
  const jeans = data.filter((product) => product.category === "jeans").slice(0, 2);
  const shirts = data.filter((product) => product.category === "shirts").slice(0, 2);
  return <div data-testid="home-page">
    <section className="hero-section"><div className="container grid min-h-[620px] items-end gap-10 pb-14 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:pb-20"><div className="relative z-10 max-w-2xl"><p className="eyebrow" data-testid="hero-eyebrow">ULHASNAGAR 5 · MAHARASHTRA</p><h1 data-testid="hero-title">Kapda<br /><em>Godam</em></h1><p className="hero-subtitle" data-testid="hero-subtitle">Wholesale Jeans & Shirts</p><p className="mt-5 max-w-lg text-base leading-8 text-slate-300" data-testid="hero-description">Quality fashion wear at wholesale prices. Reliable bulk lots, clear MOQs, and direct support for retailers across India.</p><div className="mt-9 flex flex-wrap gap-3"><Button render={<Link to="/jeans" />} data-testid="hero-view-jeans-button">View Jeans <ArrowRight size={16} /></Button><Button variant="outline" render={<Link to="/shirts" />} data-testid="hero-view-shirts-button">View Shirts</Button></div><Link to="/wholesale" className="inline-flex items-center gap-2 pt-7 text-sm font-bold uppercase tracking-widest text-amber-400 hover:text-amber-300" data-testid="hero-wholesale-enquiry-link">Wholesale enquiry <ArrowRight size={15} /></Link></div><div className="hero-stat-panel" data-testid="hero-stat-panel"><p className="eyebrow">THE WHOLESALE STANDARD</p><div className="mt-8 grid grid-cols-2 gap-5"><div className="stat-box"><strong>30–50</strong><span>Piece starting MOQs</span></div><div className="stat-box"><strong>48h</strong><span>Dispatch on ready lots</span></div><div className="stat-box"><strong>02</strong><span>Focused categories</span></div><div className="stat-box"><strong>01</strong><span>Direct buying desk</span></div></div><div className="mt-9 border-t border-white/15 pt-5 text-sm leading-6 text-slate-400">Denim and shirting programs made for shop owners, resellers and distributors.</div></div></div></section>
    <section className="trust-bar" data-testid="wholesale-trust-bar"><div className="container grid gap-5 py-7 sm:grid-cols-2 lg:grid-cols-4"><Trust icon={<Factory />} title="Direct factory rates" /><Trust icon={<Layers3 />} title="MOQ-led buying" /><Trust icon={<Truck />} title="Fast dispatch" /><Trust icon={<UsersRound />} title="Retailer-first support" /></div></section>
    <section className="section container" data-testid="featured-section"><div className="section-heading"><div><p className="eyebrow">01 / CURATED BULK LOTS</p><h2>Built for your<br /><span>next rack.</span></h2></div><Link to="/jeans" className="text-link" data-testid="featured-catalog-link">See all catalog <ArrowRight size={16} /></Link></div><div className="grid gap-6 md:grid-cols-2">{jeans.map((product) => <ProductCard key={product.id} product={product} />)}</div><div className="mt-20 grid gap-6 md:grid-cols-2">{shirts.map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
    <section className="section about-strip" data-testid="why-choose-section"><div className="container grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">02 / WHY KAPDA GODAM</p><h2>Less noise.<br /><span>More stock.</span></h2><p className="mt-7 max-w-lg leading-8 text-slate-400">We keep the range focused so your buying stays predictable. Every lot is built around commercially proven fits, sizes, and colors — then supported by a direct owner-led desk.</p><Link to="/about" className="text-link mt-8" data-testid="about-story-link">Read our story <ArrowRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2">{["Commercial fits that move", "Clear piece-level pricing", "Size runs made for shops", "Owner-led order confirmation"].map((item, index) => <div className="benefit-row" key={item} data-testid={`benefit-${index + 1}`}><span><Check size={16} /></span><p>{item}</p></div>)}</div></div></section>
    <section className="section container"><div className="contact-callout" data-testid="home-contact-callout"><div><p className="eyebrow">03 / OPEN A BUYING DESK</p><h2>Ready to fill<br /><span>your shelves?</span></h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">Send us your requirement. We will confirm availability, sizing and dispatch details directly.</p></div><Button render={<Link to="/contact" />} data-testid="home-contact-button">Start wholesale enquiry <ArrowRight size={16} /></Button></div></section>
  </div>;
}

function Trust({ icon, title }: { icon: ReactNode; title: string }) { return <div className="flex items-center gap-3 text-sm font-semibold text-slate-200" data-testid={`trust-${title.toLowerCase().replaceAll(" ", "-")}`}><span className="text-amber-400">{icon}</span>{title}</div>; }
